# bartz/pyproject.toml
#
# Copyright (c) 2024, Giacomo Petrillo
#
# This file is part of bartz.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bartz"
authors = [
  { name="Giacomo Petrillo", email="info@giacomopetrillo.com" },
]
description = "A jax implementation of BART"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Development Status :: 3 - Alpha",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    'jax>=0.4.23',
    'jaxlib>=0.4.23',
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "bartz.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[project.urls]
"Homepage" = "https://github.com/Gattocrucco/bartz"
"Bug Tracker" = "https://github.com/Gattocrucco/bartz/issues"

[project.optional-dependencies]

dev = [ # to work locally on bartz
    "jax",
    "jaxlib",
    "sphinx",
    "myst-parser",
    "numpydoc",
    "pytest",
    "coverage[toml]",
    "twine",
    "ipython",
    "build",
]

test-tools = [ # tools to run the unit tests on CI
    "pytest",
    "coverage[toml]",
]

test-deps = [ # dependencies to install to run the unit tests on CI
    "jax",
    "jaxlib",
]

test-deps-old = [ # to run the unit tests on CI, with minimum supported dependencies
    "jax==0.4.23",
    "jaxlib==0.4.23",
]

docs = [ # to run examples, documentation code, and build documentation on CI
    "jax",
    "jaxlib",
    "numpydoc",
    "coverage[toml]",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
]
addopts = [
    "-r xXfE",
    "--pdbcls=IPython.terminal.debugger:TerminalPdb",
    "--durations=3",
]

# I wanted to use `--import-mode=importlib`, but it breaks importing submodules,
# in particular `from . import util`.

[tool.coverage.run]
branch = true
source = ["bartz"]

[tool.coverage.report]
show_missing = true

[tool.coverage.html]
show_contexts = true

[tool.coverage.paths]
# the first path in each list must be the source directory in the machine that's
# generating the coverage report

github = [
    '/home/runner/work/bartz/bartz/src/bartz/',
    '/Users/runner/work/bartz/bartz/src/bartz/',
    'D:\a\bartz\bartz\src\bartz\',
    '/Library/Frameworks/Python.framework/Versions/*/lib/python*/site-packages/bartz/',
    '/Users/runner/hostedtoolcache/Python/*/*/lib/python*/site-packages/bartz/',
    '/opt/hostedtoolcache/Python/*/*/lib/python*/site-packages/bartz/',
    'C:\hostedtoolcache\windows\Python\*\*\Lib\site-packages\bartz\',
]

local = [
    'src/bartz/',
    '/home/runner/work/bartz/bartz/src/bartz/',
    '/Users/runner/work/bartz/bartz/src/bartz/',
    'D:\a\bartz\bartz\src\bartz\',
    '/Library/Frameworks/Python.framework/Versions/*/lib/python*/site-packages/bartz/',
    '/Users/runner/hostedtoolcache/Python/*/*/lib/python*/site-packages/bartz/',
    '/opt/hostedtoolcache/Python/*/*/lib/python*/site-packages/bartz/',
    'C:\hostedtoolcache\windows\Python\*\*\Lib\site-packages\bartz\',
]
